language: python
python:
  - "3.8"

services:
  - postgresql

before_script:
  - psql -c 'create database mydb;' -U postgres

install:
  - pip install -r requirements.txt

script:
  - python manage.py test